[package]
name = "aissh-ipc"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_System_Pipes",
  "Win32_System_Threading",
] }
