import React,{useEffect,useRef,useState}from"react";
import{createRoot}from"react-dom/client";
import{invoke}from"@tauri-apps/api/core";
import{Terminal}from"@xterm/xterm";
import{FitAddon}from"@xterm/addon-fit";
import{Activity,FolderOpen,RefreshCw,Save,ShieldAlert,TerminalSquare}from"lucide-react";
import"@xterm/xterm/css/xterm.css";import"./styles.css";

type SessionStatus="connecting"|"ready"|"exec_running"|"pty_open"|"idle"|"disconnected"|"interrupted"|"closed"|"failed";
type Session={id:string;target_id:string;target_name:string;purpose:string;client_name:string;status:SessionStatus;current_command:string|null;last_exit_code:number|null;recording_truncated:boolean;host_fingerprint:string|null;created_at:string;updated_at:string;closed_at:string|null};
type Target={id:string;name:string;host:string;port:number;username:string;host_verification:boolean};
type Event={sequence:number;stream:"stdout"|"stderr"|"pty"|"system";payload:number[]};
type ResponseData={kind:"targets";data:Target[]}|{kind:"sessions";data:Session[]}|{kind:"session";data:Session}|{kind:"events";data:{events:Event[];next_sequence:number;has_more:boolean}};
const sessionId=new URLSearchParams(location.search).get("session");

function App(){return sessionId?<SessionWindow id={sessionId}/>:<SessionList/>}
function SessionList(){
 const[sessions,setSessions]=useState<Session[]>([]),[targets,setTargets]=useState<Target[]>([]),[selectedTarget,setSelectedTarget]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[retention,setRetention]=useState(30);
 const load=async()=>{setBusy(true);try{const value=await invoke<ResponseData>("sessions",{includeHistory:true});if(value.kind==="sessions")setSessions(value.data);setError("")}catch(e){setError(String(e))}finally{setBusy(false)}};
 useEffect(()=>{void load();invoke<number>("retention_days").then(setRetention).catch(e=>setError(String(e)));invoke<ResponseData>("targets").then(v=>{if(v.kind==="targets"){setTargets(v.data);setSelectedTarget(v.data[0]?.id||"")}}).catch(e=>setError(String(e)));const timer=setInterval(load,2000);return()=>clearInterval(timer)},[]);
 return <main className="page"><Header actions={<><label className="retention"><span>Retention</span><input aria-label="Retention days" type="number" min={1} max={3650} value={retention} onChange={e=>setRetention(Number(e.target.value))}/><span>days</span></label><button className="icon" title="Save retention" onClick={()=>invoke("set_retention_days",{days:retention}).then(load).catch(e=>setError(String(e)))}><Save size={17}/></button><button className="icon" title="Reload configuration" onClick={()=>invoke("reload_config").then(load).catch(e=>setError(String(e)))}><RefreshCw size={17}/></button><button className="icon" title="Open configuration directory" onClick={()=>invoke("open_config")}><FolderOpen size={17}/></button></>}/><section className="settings-strip"><select aria-label="Target to test" value={selectedTarget} onChange={e=>setSelectedTarget(e.target.value)}>{targets.map(t=><option key={t.id} value={t.id}>{t.name} - {t.username}@{t.host}:{t.port}</option>)}</select><button disabled={!selectedTarget} onClick={()=>{setBusy(true);invoke("test_target",{targetId:selectedTarget}).then(()=>setError("")).catch(e=>setError(String(e))).finally(()=>setBusy(false))}}><Activity size={16}/>Test target</button></section><section className="content"><div className="section-title"><div><h2>Sessions</h2><span>{sessions.length} recorded</span></div><span className="readonly">Observer</span></div>{error&&<div className="error">{error}</div>}<div className="table-wrap"><table><thead><tr><th>Target</th><th>Status</th><th>Current command</th><th>AI client</th><th>Started</th></tr></thead><tbody>{sessions.map(item=><tr key={item.id} onDoubleClick={()=>location.href=`?session=${item.id}`}><td><strong>{item.target_name}</strong><small>{item.id.slice(0,8)}</small></td><td><Status value={item.status}/></td><td className="command">{item.current_command||"-"}</td><td>{item.client_name}</td><td>{new Date(item.created_at).toLocaleString()}</td></tr>)}{!sessions.length&&!busy&&<tr><td colSpan={5} className="empty">No sessions recorded</td></tr>}</tbody></table></div></section></main>
}
function SessionWindow({id}:{id:string}){
 const[session,setSession]=useState<Session|null>(null),[error,setError]=useState("");const host=useRef<HTMLDivElement>(null),terminal=useRef<Terminal|null>(null),sequence=useRef(0);
 useEffect(()=>{if(!host.current)return;const term=new Terminal({disableStdin:true,convertEol:false,cursorBlink:false,fontFamily:"SFMono-Regular, Menlo, monospace",fontSize:13,theme:{background:"#111416",foreground:"#e7ebed",cursor:"#111416",red:"#ff6b5f",green:"#80c995",yellow:"#e5c07b",blue:"#75a7ff",magenta:"#c792ea",cyan:"#64d8cb",white:"#e7ebed"},scrollback:10000});const fit=new FitAddon();term.loadAddon(fit);term.open(host.current);fit.fit();terminal.current=term;const resize=()=>fit.fit();window.addEventListener("resize",resize);return()=>{window.removeEventListener("resize",resize);term.dispose()}},[]);
 useEffect(()=>{let active=true;const poll=async()=>{try{const status=await invoke<ResponseData>("session_status",{sessionId:id});if(status.kind==="session")setSession(status.data);let more=true;while(active&&more){const output=await invoke<ResponseData>("session_events",{sessionId:id,afterSequence:sequence.current,maxBytes:65536});if(output.kind!=="events")break;for(const event of output.data.events){terminal.current?.write(new Uint8Array(event.payload));sequence.current=Math.max(sequence.current,event.sequence)}more=output.data.has_more}setError("")}catch(e){setError(String(e))}};void poll();const timer=setInterval(poll,250);return()=>{active=false;clearInterval(timer)}},[id]);
 return <main className="session-page"><Header/><section className="session-meta"><div><span className="label">Target</span><strong>{session?.target_name||"Connecting"}</strong></div><div><span className="label">Session</span><code>{id}</code></div><div><span className="label">AI client</span><span>{session?.client_name||"-"}</span></div><div><span className="label">Status / exit</span>{session&&<Status value={session.status}/>}<small>{session?.last_exit_code==null?"Exit pending":`Exit ${session.last_exit_code}`}</small></div></section><div className="warning"><ShieldAlert size={16}/><span>{session?.recording_truncated?"Recording limit reached; live output continues":"Host verification is disabled"}</span><code>{session?.host_fingerprint||"Fingerprint pending"}</code></div>{error&&<div className="error">{error}</div>}<section className="terminal-shell"><div className="terminal-bar"><span><TerminalSquare size={16}/>Read-only terminal</span><code>{session?.current_command||"No foreground command"}</code></div><div className="terminal" ref={host}/></section></main>
}
function Header({actions}:{actions?:React.ReactNode}){return <header><div className="brand"><div className="brand-mark">AI</div><div><h1>AI SSH</h1><span>Local session observer</span></div></div><div className="actions">{actions}</div></header>}
function Status({value}:{value:SessionStatus}){return <span className={`status status-${value}`}><i/>{value.replace("_"," ")}</span>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
